unpackaged/main/default/objects/SFDC_Candidate__c/SFDC_Candidate__c.object-meta.xml
<CustomObject>
    <description>Candidates selected for consideration of a job</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SFDC_Candidate_Reference__c/SFDC_Candidate_Reference__c.object-meta.xml
<CustomObject>
    <description>Candidate References</description>
    <label>Candidate Reference</label>
    <nameField>
        <displayFormat>Reference-{0000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SFDC_Job__c/SFDC_Job__c.object-meta.xml
<CustomObject>
    <description>Job Position to be filled</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SFDC_Job__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/SFDC_Job__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00-Draft</fullName>
                <default>true</default>
                <label>00-Draft</label>
            </value>
            <value>
                <fullName>01-Open</fullName>
            </value>
            <value>
                <fullName>02-Sourcing</fullName>
            </value>
            <value>
                <fullName>03-Interviewing</fullName>
            </value>
            <value>
                <fullName>04-Offer Negotiation</fullName>
            </value>
            <value>
                <fullName>05-Routing Offer</fullName>
            </value>
            <value>
                <fullName>06-Offer Sent</fullName>
            </value>
            <value>
                <fullName>07-Offer Accepted</fullName>
            </value>
            <value>
                <fullName>08-Filled</fullName>
            </value>
            <value>
                <fullName>09-On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/JobListingController_Test.cls
@isTest
public class JobListingController_Test {

    @isTest
    public static void testfetchAllJobs() {
        SFDC_Job__c job = new SFDC_Job__c();
        job.Name = 'Salesforce Developer';
        job.Job_Status__c = '01-Open';
        job.Job_Description__c = 'description';
        insert job;
        
        JobListingController.fetchAllJobs();
        
        JobListingController.fetchSpecificJob(job.Id);
        
        Id candidateId = JobListingController.applicationSubmit(job.Id, '{"attributes":{"type":"SFDC_Candidate__c"},"Name":"Anshul Arora"}');
        
        JobListingController.SaveFile(candidateId, 'file.docx', 'test string', '.doc', null);
    }
    
    @isTest
    public static void testFetchAndSubmitReferences() {
        SFDC_Job__c job = new SFDC_Job__c();
        job.Name = 'Salesforce Developer';
        job.Job_Status__c = '01-Open';
        job.Job_Description__c = 'description';
        insert job;
        
        SFDC_Candidate_Reference__c ref = new SFDC_Candidate_Reference__c();
        ref.Phone__c = '7845125478';
        ref.Email__c = 'test@trifinlabs.com';
        ref.Name__c = 'Test';
        
        Id candidateId = JobListingController.applicationSubmit(job.Id, '{"attributes":{"type":"SFDC_Candidate__c"},"Name":"Anshul Arora"}');
        
        JobListingController.createReferences(
            candidateId
        	, new List<SFDC_Candidate_Reference__c> {ref}
        );
        
        SFDC_Candidate_Reference__c reference = [SELECT Id FROM SFDC_Candidate_Reference__c LIMIT 1];
        JobListingController.fetchSpecificReference(reference.Id);
        JobListingController.submitReference(reference);
		        
    }
}