unpackaged/main/default/objects/SFDC_Candidate__c/SFDC_Candidate__c.object-meta.xml
<CustomObject>
    <description>Candidates selected for consideration of a job</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SFDC_Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Applied for Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFDC_Candidate_Reference__c/SFDC_Candidate_Reference__c.object-meta.xml
<CustomObject>
    <description>Candidate References</description>
    <label>Candidate Reference</label>
    <nameField>
        <displayFormat>Reference-{0000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SFDC_Candidate_Reference__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>SFDC_Candidate__c</referenceTo>
    <relationshipLabel>Candidate References</relationshipLabel>
    <relationshipName>Candidate_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SFDC_Candidate_Reference__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SFDC_Job__c/SFDC_Job__c.object-meta.xml
<CustomObject>
    <description>Job Position to be filled</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SFDC_Job__c/fields/Job_Compensation__c.field-meta.xml
<CustomField>
    <fullName>Job_Compensation__c</fullName>
    <label>Job Compensation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFDC_Job__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/SFDC_Job__c/fields/Job_Filled__c.field-meta.xml
<CustomField>
    <fullName>Job_Filled__c</fullName>
    <label>Job Filled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SFDC_Job__c/fields/Job_Overview__c.field-meta.xml
<CustomField>
    <fullName>Job_Overview__c</fullName>
    <label>Job Overview</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SFDC_Job__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00-Draft</fullName>
                <default>true</default>
                <label>00-Draft</label>
            </value>
            <value>
                <fullName>01-Open</fullName>
            </value>
            <value>
                <fullName>02-Sourcing</fullName>
            </value>
            <value>
                <fullName>03-Interviewing</fullName>
            </value>
            <value>
                <fullName>04-Offer Negotiation</fullName>
            </value>
            <value>
                <fullName>05-Routing Offer</fullName>
            </value>
            <value>
                <fullName>06-Offer Sent</fullName>
            </value>
            <value>
                <fullName>07-Offer Accepted</fullName>
            </value>
            <value>
                <fullName>08-Filled</fullName>
            </value>
            <value>
                <fullName>09-On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SFDC_Job__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SFDC_Job_Candidate__c/SFDC_Job_Candidate__c.object-meta.xml
<CustomObject>
    <description>Link Object</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JID{000000}</displayFormat>
        <label>Job Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SFDC_Job_Candidate__c/fields/SFDC_Candidate__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>SFDC_Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>R00N30000001WXBxEAO</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SFDC_Job_Candidate__c/fields/SFDC_Job__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Job__c</fullName>
    <label>Job</label>
    <referenceTo>SFDC_Job__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>R00N30000001WXBwEAO</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SFDC_Job_Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(SFDC_Candidate__r.Application_Status__c)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/JobListingController.cls
public without sharing class JobListingController {

    @auraEnabled
    public static List<SFDC_Job__c> fetchAllJobs() {
        return [
            SELECT Id, Name, Job_Number__c, Job_Type__c,Job_Description__c, Job_Overview__c,
                Job_Compensation__c
            FROM SFDC_Job__c
            WHERE Job_Status__c != '00-Draft' AND Job_Filled__c != 'Yes'
        ];
    }
    
    @auraEnabled
    public static SFDC_Job__c fetchSpecificJob(Id jobId) {
        return [
            SELECT Id, Name, Job_Number__c, Job_Type__c,Job_Description__c, Job_Overview__c,
                Job_Compensation__c
            FROM SFDC_Job__c
            WHERE Id = :jobId
        ];
    }
    
    @auraEnabled
    public static Id applicationSubmit(Id jobId, String candidate) {
        try {
            SFDC_Candidate__c applyingCandidate = (SFDC_Candidate__c)JSON.deserialize(candidate, SFDC_Candidate__c.class);
            insert applyingCandidate;
            
            //create the junction for application
            SFDC_Job_Candidate__c application = new SFDC_Job_Candidate__c(SFDC_Candidate__c = applyingCandidate.Id, SFDC_Job__c = jobId);
            insert application;
            
            return applyingCandidate.Id;
        
        } catch (Exception e) {
            throw new AuraHandledException('Something went wrong: '+ e.getMessage());    
        }
        
    }
    
    @AuraEnabled
    public static Id SaveFile(Id parentId, String fileName, String base64Data, String contentType, Id fileId) {
        try {
            base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
            Attachment attach = new Attachment();
            attach.parentId = parentId;
            attach.Body = EncodingUtil.base64Decode(base64Data);
            attach.Name = fileName;
            attach.ContentType = contentType;
            attach.Id = String.isNotBlank(fileId) ? fileId : null;
            upsert attach;
            return attach.Id;
        
        } catch (Exception e) {
            throw new AuraHandledException('Something went wrong: '+ e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void createReferences(Id candidateId, List<SFDC_Candidate_Reference__c> references) {
        List<SFDC_Candidate_Reference__c> allReferencesToBeInserted = new List<SFDC_Candidate_Reference__c>();
        
        for (SFDC_Candidate_Reference__c eachReference : references) {
            eachReference.Candidate__c = candidateId;
            allReferencesToBeInserted.add(eachReference);
        }
        
        try {
            insert allReferencesToBeInserted;    
        } catch (Exception e) {
            throw new AuraHandledException('Something went wrong: '+ e.getMessage());
        }
    }
    
   @AuraEnabled
    public static SFDC_Candidate_Reference__c fetchSpecificReference(Id referenceId) {
        
        return [
            SELECT Id, Candidate__c, Candidate__r.Name, Candidate__r.Position__c 
            FROM SFDC_Candidate_Reference__c 
            WHERE Id = :referenceId
        ];
    }
    
    @AuraEnabled
    public static void submitReference(SFDC_Candidate_Reference__c reference) {
        
        if (reference == null) {
            return;
        }
        
        reference.Status__c = 'Complete';
        try {
            update reference;
        } catch(Exception e) {
            throw new AuraHandledException('Something went wrong: '+ e.getMessage());
        }
    }
}